<div class="jumbotron">
    <h1>Welcome to Zend Framework 2</h1>
    <p><?php echo sprintf($this->translate('You are currently running Zend Framework version %s. This skeleton can serve as a simple starting point for you to begin building your neustar theme application on ZF2.'), \Zend\Version\Version::VERSION) ?></p>
    <p>See options below for help on getting started.</p>
    <p><a class="btn btn-success btn-lg" href="https://github.com/neuweb/ZendSkeletonApplication" target="_blank"><?php echo $this->translate('Neustar Skeleton on GitHub') ?> &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Using Composer to Install') ?></h3>
            </div>
            <div class="panel-body">
                <p>The recommended way to get a working copy of this project is to clone the repository and use <code>composer</code> to install dependencies using the <code>create-project</code> command:</p>
                <pre>curl -s https://getcomposer.org/installer | php --
php composer.phar create-project neuweb/zendskeletonapplication /path/to/your/project</pre>
            </div>
        </div>
    </div>

    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Download from GitHub') ?></h3>
            </div>
            <div class="panel-body">
                <p>Alternately, clone the repository and manually invoke <code>composer</code> using the shipped <code>composer.phar</code>:</p>
                <pre>cd my/project/dir
git clone git@github.com:neuweb/ZendSkeletonApplication.git
cd ZendSkeletonApplication
php composer.phar self-update
php composer.phar install</pre>
                <p>(The <code>self-update</code> directive is to ensure you have an up-to-date <code>composer.phar</code> available.)</p>
                <p>Another alternative for downloading the project is to grab it via <code>curl</code>, and then pass it to <code>tar</code>:</p>
                <pre>cd my/project/dir
curl -#L https://github.com/neuweb/ZendSkeletonApplication/tarball/master | tar xz --strip-components=1</pre>
                <p>You would then invoke <code>composer</code> to install dependencies per the previous example.</p>
                <p>Alternatively, you can install using native git submodules:</p>
                <pre>git clone git://github.com/neuweb/ZendSkeletonApplication.git --recursive</pre>
            </div>
        </div>
    </div>

    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Download Neustar HTML only') ?></h3>
            </div>
            <div class="panel-body">
                <p>Click the link below to download the HTML so you can integrate into your application manually. The CSS is stored on our CDN and the favicon is embedded into the page.</p>
                <p><a class="btn btn-success pull-right" href="/download/index.html" download="index.html"><?php echo $this->translate('Download') ?> &raquo;</a></p>
            </div>
        </div>
    </div>
</div>