<section class="breadcrumbs">
    <div class="container">
        <ol class="breadcrumb">
            <li><a href="#">Home</a></li>
            <li><a href="#">Library</a></li>
            <li class="active">Data</li>
        </ol>
    </div>
</section>

<section class="full intro">
    <div class="container">
        <div class="row">
            <h1 class="col-md-12">Neustar Layout</h1>
        </div>
    </div>
</section>

<section class="full localnav">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <nav class="">
                    <ul>
                        <li class="active"><a href="#">Overview</a></li>
                        <li><a href="#">Our History</a></li>
                        <li><a href="#">Leadership</a></li>
                        <li><a href="#">Corporate Responsibility</a></li>
                        <li><a href="#">Neutrality</a></li>
                    </ul>
                    <div class="clearfix"></div>
                </nav>
            </div>
        </div>
    </div>
</section>

<section class="full jumbotron">
    <div class="container">
        <div class="col-md-12 ">
            <h2>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</h2>
        </div>

        <div class="clr">&nbsp;</div>
    </div>
</section>

<section class="full wrapper">
    <div class="container">
        <article class="col-md-12 main">
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec fermentum tellus, sit amet tincidunt lorem. Morbi viverra hendrerit purus et lacinia. In vulputate massa sed aliquet vulputate. Integer rhoncus dolor tortor, nec adipiscing tellus feugiat at. Etiam id eros et nisi suscipit sollicitudin. Praesent mollis, magna sed ultricies pharetra, sem ligula dignissim odio, ultrices faucibus nulla augue placerat nulla. In malesuada interdum nulla. Mauris venenatis tortor ut nunc cursus porta. Nunc ut massa orci. Ut ullamcorper blandit libero, ut lacinia mauris tristique et. Integer dignissim aliquam velit, et congue arcu sollicitudin vitae. Maecenas fermentum, leo vitae iaculis scelerisque, diam eros cursus ipsum, at interdum nisi purus in turpis. Donec a auctor mi, quis facilisis elit. Proin aliquet ante a semper volutpat. Aenean eget erat ut metus vulputate pellentesque non sit amet ante. Donec vestibulum tincidunt elit sed suscipit.
            </p>

            <p>Pellentesque sed tempor nisi. Ut in ligula feugiat, pellentesque risus in, molestie ipsum. Proin non erat leo. Maecenas molestie imperdiet lacus in venenatis. Vestibulum aliquet velit non nibh tincidunt, at tempus purus porta. Suspendisse iaculis vitae dolor quis auctor. Curabitur hendrerit, libero ut imperdiet scelerisque, erat ligula congue quam, varius volutpat leo magna a magna. Pellentesque convallis fermentum tempus. <a href="#">Link</a></p>

            <p><a class="btn btn-default btn-lg" href="/it-security-services">Learn more</a></p>
            <p><a class="btn btn-default" href="/it-security-services">Learn</a></p>
            <p><a class="btn btn-default btn-sm" href="/it-security-services">Learn</a></p>
            <p><a class="btn btn-default btn-xs" href="/it-security-services">Learn</a></p>

            <p><a class="btn btn-primary btn-lg" href="/it-security-services">Learn more</a></p>
            <p><a class="btn btn-primary" href="/it-security-services">Learn</a></p>
            <p><a class="btn btn-primary btn-sm" href="/it-security-services">Learn</a></p>
            <p><a class="btn btn-primary btn-xs" href="/it-security-services">Learn</a></p>
            <p><a class="btn btn-primary btn-block" href="/it-security-services">Learn</a></p>

            <!-- Standard button -->
            <button type="button" class="btn btn-default">Default</button>

            <!-- Provides extra visual weight and identifies the primary action in a set of buttons -->
            <button type="button" class="btn btn-primary">Primary</button>

            <!-- Indicates a successful or positive action -->
            <button type="button" class="btn btn-success">Success</button>

            <!-- Contextual button for informational alert messages -->
            <button type="button" class="btn btn-info">Info</button>

            <!-- Indicates caution should be taken with this action -->
            <button type="button" class="btn btn-warning">Warning</button>

            <!-- Indicates a dangerous or potentially negative action -->
            <button type="button" class="btn btn-danger">Danger</button>

            <!-- Indicates a dangerous or potentially negative action -->
            <button type="button" class="btn btn-cancel">Cancel</button>

            <!-- Deemphasize a button by making it look like a link while maintaining button behavior -->
            <button type="button" class="btn btn-link">Link</button>
        </article>
        <hr class="split">
        <div class="col-md-4">
            <h3>Lorem Ipsum</h3>

            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec fermentum tellus, sit amet tincidunt lorem. Morbi viverra hendrerit purus et lacinia. In vulputate massa sed aliquet vulputate. Integer rhoncus dolor tortor, nec adipiscing tellus feugiat at. Etiam id eros et nisi suscipit sollicitudin. Praesent mollis, magna sed ultricies pharetra, sem ligula dignissim odio, ultrices faucibus nulla augue placerat nulla.</p>

            <p><a class="btn btn-default" href="/marketing-services">Learn more</a></p>
        </div>

        <div class="col-md-4">
            <h3>Lorem Ipsum</h3>

            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec fermentum tellus, sit amet tincidunt lorem. Morbi viverra hendrerit purus et lacinia. In vulputate massa sed aliquet vulputate. Integer rhoncus dolor tortor, nec adipiscing tellus feugiat at. Etiam id eros et nisi suscipit sollicitudin. Praesent mollis, magna sed ultricies pharetra, sem ligula dignissim odio, ultrices faucibus nulla augue placerat nulla.</p>

            <p><a class="btn btn-default" href="/it-security-services">Learn more</a></p>
        </div>

        <div class="col-md-4">
            <h3>Lorem Ipsum</h3>

            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec fermentum tellus, sit amet tincidunt lorem. Morbi viverra hendrerit purus et lacinia. In vulputate massa sed aliquet vulputate. Integer rhoncus dolor tortor, nec adipiscing tellus feugiat at. Etiam id eros et nisi suscipit sollicitudin. Praesent mollis, magna sed ultricies pharetra, sem ligula dignissim odio, ultrices faucibus nulla augue placerat nulla.</p>

            <p><a class="btn btn-primary" href="/registry-other-services">Learn more</a></p>
        </div>
    </div>
</section>


