<section class="breadcrumbs">
    <div class="container">
        <ol class="breadcrumb">
            <li><a href="#">Home</a></li>
            <li><a href="#">Library</a></li>
            <li class="active">Data</li>
        </ol>
    </div>
</section>

<section class="full intro">
    <div class="container">
        <div class="row">
            <h1 class="col-md-12">Neustar Layout</h1>
        </div>
    </div>
</section>


<section class="full wrapper">
    <div class="container">
        <article class="col-md-12 main">
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec fermentum tellus, sit amet tincidunt lorem. Morbi viverra hendrerit purus et lacinia. In vulputate massa sed aliquet vulputate. Integer rhoncus dolor tortor, nec adipiscing tellus feugiat at. Etiam id eros et nisi suscipit sollicitudin. Praesent mollis, magna sed ultricies pharetra, sem ligula dignissim odio, ultrices faucibus nulla augue placerat nulla. In malesuada interdum nulla. Mauris venenatis tortor ut nunc cursus porta. Nunc ut massa orci. Ut ullamcorper blandit libero, ut lacinia mauris tristique et. Integer dignissim aliquam velit, et congue arcu sollicitudin vitae. Maecenas fermentum, leo vitae iaculis scelerisque, diam eros cursus ipsum, at interdum nisi purus in turpis. Donec a auctor mi, quis facilisis elit. Proin aliquet ante a semper volutpat. Aenean eget erat ut metus vulputate pellentesque non sit amet ante. Donec vestibulum tincidunt elit sed suscipit.
            </p>
        </article>
    </div>
</section>


